name: API Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/api-tests.yml'
      - 'docker-compose.test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/api-tests.yml'
      - 'docker-compose.test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Check Docker and Docker Compose versions
      run: |
        docker --version
        docker compose version
    
    - name: Run API tests in Docker
      run: |
        chmod +x ./compose.sh
        ./compose.sh test run
      
    - name: Cleanup
      if: always()
      run: |
        ./compose.sh test down -v
